### ISSUE TITLE
Heatpump not detected

### ISSUE THREAD

**Issue by andriuskr** [djbulsink/panasonic_ac#15]
Hi,

Plugin not detecting heatpump

**Comment by djbulsink** [comment]
Hi @andriuskr ,

I don't have a heatpump myself, so I can't test it myself. So can you please enable the debug logging for this integration. 
```yaml
logger:
  default: warning
  logs:
    custom_components.panasonic_ac.climate: debug
```

And send me the log messages?
